import React, { Component, useState } from 'react';
import classnames from 'classnames';
import Link from 'next/link';

class Mailbox extends Component {
  constructor(props) {
    super(props);

    this.state = {
      smartPhone: false,
      sms: false,
    };
  }
  render() {
    const { smartPhone, sms } = this.state;
    return (
      <>
        <section>
          <div class="container-fluid">
            <div class="row">
              <div class="col-lg-6">
                <div class="sign-in-form">
                  <div class="signin-head">
                    <div class="dapp-header-logo">
                      <img
                        src="/images/logo-big.png"
                        alt="logo"
                        class="img-fluid"
                      />
                    </div>
                    <h2>2FA Authentication</h2>
                    <p>
                      Choose which methrod you want to <br />
                      use for 2FA code
                    </p>
                  </div>
                  <div id="auth-block">
                    <div
                      className={classnames('dapp-2f-auth-block', {
                        'auth-active': smartPhone == true,
                      })}
                      onClick={() => {
                        this.setState({
                          smartPhone: true,
                          sms: false,
                        });
                      }}
                    >
                      <div class="auth-select">
                        <img
                          src="/images/auth-check.png"
                          alt="auth-check"
                          class="img-fluid"
                        />
                      </div>
                      <div class="dapp-2f-auth-block-lft">
                        <h3>
                          Smartphone app <span>Recommended</span>
                        </h3>
                        <p>
                          2FA code will be generated by your smartphone app
                          “Google Authenticator”, available for iOS, Andriod and
                          Windows phone.
                        </p>
                      </div>
                      <div class="dapp-2f-auth-block-right">
                        <img
                          src="/images/2f-img1.png"
                          alt="logo"
                          class="img-fluid"
                        />
                      </div>
                    </div>
                    <div
                      className={classnames('dapp-2f-auth-block mab-32', {
                        'auth-active': sms == true,
                      })}
                      onClick={() => {
                        this.setState({
                          smartPhone: false,
                          sms: true,
                        });
                      }}
                    >
                      <div class="auth-select">
                        <img
                          src="/images/auth-check.png"
                          alt="auth-check"
                          class="img-fluid"
                        />
                      </div>
                      <div class="dapp-2f-auth-block-lft">
                        <h3>SMS/Phone Request</h3>
                        <p>
                          Sends 2FA code via SMS or Phone <br />
                          call.
                        </p>
                      </div>
                      <div class="dapp-2f-auth-block-right">
                        <img
                          src="/images/2f-img2.png"
                          alt="logo"
                          class="img-fluid"
                        />
                      </div>
                    </div>
                  </div>
                  <div class="">
                    <Link
                      href={
                        smartPhone
                          ? '/Authentication/ConfirmNoAuth'
                          : sms
                          ? '/Authentication/ConfirmNoSms1'
                          : ''
                      }
                    >
                      <button type="submit" class="bttn-primary">
                        Next
                      </button>
                    </Link>
                  </div>
                </div>
              </div>
              <div class="col-lg-6 p-0">
                <div class="sign-up-bg-image">
                  <div class="twitwr-img">
                    <a href="#">
                      <img
                        src="/images/twitter.png"
                        alt="twitter"
                        class="img-fluid"
                      />
                    </a>
                  </div>
                  <div>
                    <img
                      src="/images/signup.png"
                      alt="signup"
                      class="img-fluid"
                    />
                  </div>
                  <div class="top-corner">
                    <img
                      src="/images/img1.png"
                      alt="signup"
                      class="img-fluid"
                    />
                  </div>
                  <div class="bottom-corner">
                    <img
                      src="/images/img2.png"
                      alt="signup"
                      class="img-fluid"
                    />
                  </div>

                  <div class="linkedin-img">
                    <a href="#">
                      <img
                        src="/images/linkedin.png"
                        alt="linkedin"
                        class="img-fluid"
                      />
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </>
    );
  }
}
export default Mailbox;
